const fragrances = [
    {
        id: 'elysian',
        name: 'ELYSIAN',
        family: 'Fresh / Fruity',
        shortDescription: 'A vibrant burst of crisp green apples and citrus, floating on a delicate layer of clean white musk.',
        topNotes: ['Bergamot'],
        middleNotes: ['Green Apple'],
        baseNotes: ['Whipped Cream'],
        usage: ['All Day', 'All Usage', 'Female'],
        performance: { sillage: 75, projection: 85, longevity: 70 },
        colorTheme: '#7CFC00',
        image: 'assets/elysian.jpeg',
        tagline: 'The essence of pure, untouched vitality.',
        price: { '50ml': 129, '100ml': 189 }
    },
    {
        id: 'harmonious-reflection',
        name: 'HARMONIOUS REFLECTION',
        family: 'Aquatic / Woody',
        shortDescription: 'Deep oceanic accords meet rich, mysterious woods in a perfectly balanced midnight reflection.',
        topNotes: ['Passion Fruit', 'Peach', 'Pear', 'Raspberry', 'Currant Leaf'],
        middleNotes: ['Heliotrope', 'Lily Of The Valley'],
        baseNotes: ['Musk', 'Sandalwood', 'Vanilla', 'Patchouli'],
        usage: ['All Day', 'All Usage', 'Unisex'],
        performance: { sillage: 85, projection: 70, longevity: 80 },
        colorTheme: '#005f73',
        image: 'assets/harmonious_reflection.jpeg',
        tagline: 'Dive into the depths of your inner tranquility.',
        price: { '50ml': 149, '100ml': 209 }
    },
    {
        id: 'trail-of-celestia',
        name: 'TRAIL OF CELESTIA',
        family: 'Floral / Oriental',
        shortDescription: 'An ethereal journey through celestial gardens, with intoxicating night-blooming jasmine and warm vanilla.',
        topNotes: ['Lavender', 'Mandarin', 'Black Currant', 'Petitgrain'],
        middleNotes: ['Orange Blossom', 'Jasmine'],
        baseNotes: ['Vanilla', 'Musk', 'Cedar', 'Ambergris'],
        usage: ['Evening - Night', 'All Usage', 'Female'],
        performance: { sillage: 85, projection: 90, longevity: 85 },
        colorTheme: '#4b0082',
        image: 'assets/trail_of_celestia.jpeg',
        tagline: 'Leave a trail of stardust wherever you go.',
        price: { '50ml': 169, '100ml': 239 }
    },
    {
        id: 'orions-oblige',
        name: "ORION'S OBLIGE",
        family: 'Spicy / Amber',
        shortDescription: 'A bold, cosmic blend of warm spices and glowing amber, radiating with fiery intensity.',
        topNotes: ['Mandarin', 'Fresh Pineapple', 'Bergamot', 'Saffron', 'Black Currant', 'Apple'],
        middleNotes: ['Jasmine'],
        baseNotes: ['Ambroxan', 'Musk', 'Birch', 'Oakmoss', 'Patchouli'],
        usage: ['All Day', 'All Usage', 'Male'],
        performance: { sillage: 80, projection: 85, longevity: 85 },
        colorTheme: '#dc143c',
        image: 'assets/orions_oblige.jpeg',
        tagline: 'Command the universe with fiery devotion.',
        price: { '50ml': 159, '100ml': 219 }
    },
    {
        id: 'soft-spoken',
        name: 'SOFT SPOKEN',
        family: 'Musky / Minimalist',
        shortDescription: 'A skin-scent masterpiece. Barely there, yet utterly captivating with sheer clean woods and iris.',
        topNotes: ['Pineapple', 'Granny Smith Apple', 'Mandarin'],
        middleNotes: ['Oakmoss', 'Vanilla', 'Cedarwood'],
        baseNotes: ['Dry Wood', 'Ambergris', 'Caramel', 'Musk'],
        usage: ['Night', 'All Usage', 'Male'],
        performance: { sillage: 40, projection: 50, longevity: 80 },
        colorTheme: '#8f9779',
        image: 'assets/soft_spoken.jpeg',
        tagline: 'Whisper your presence. Let them lean in.',
        price: { '50ml': 139, '100ml': 199 }
    }
];
